services:
  builder:
    container_name: rdvl-builder
    build:
      context: .
      args:
        OS: windows
        ARCH: amd64
        VERSION: sample
    volumes:
      - ./bin:/home/app/bin
    environment:
      - VERSION=sample