version: '3'

services:
  builder:
    container_name: rdvl-builder
    build:
      context: .
      args:
        OS: linux
        ARCH: arm64
    volumes:
      - ./bin:/home/app/bin
    environment:
      - TAG=local